import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

import { EdgeStoreProvider } from '../lib/edgestore';

import ToasterProvider from '@/components/providers/toast-provider';
import { ConfettiProvider } from '@/components/providers/confetti-provider';
import { ConvexClientProvider } from '@/components/providers/convex-provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Polres App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <ToasterProvider />
        <ConfettiProvider />
        <ConvexClientProvider>
          <EdgeStoreProvider>
            <main className="min-h-screen">{children}</main>
          </EdgeStoreProvider>
        </ConvexClientProvider>
      </body>
    </html>
  );
}
